services:
  script:
    container_name: cdk-streaming-script
    build: ./
    tty: true
    volumes:
      - ${HOME}/.aws/credentials:/root/.aws/credentials:ro
      - ${HOME}/.aws/config:/root/.aws/config:ro
      - .vimrc:/root/.vimrc:ro
      - ./:/workspace:cached
